name: Run Heart Analysis

on:
  workflow_call:
    inputs:
      image-name:
        # description: name of the docker image
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # -
      #   id: rm-api
      #   if: 
      # -
      #   id: rm-dareboost
      #   if: 
      # -
      #   id: rm-lighthouse
      #   if:
      # -
      #   id: rm-observatory
      #   if: 
      # -
      #   id: rm-bigquery
      #   if: 
      # -
      #   id: rm-slack
      #   if: 
      - name: Run Heart through docker container
        id: run-heart
        run: docker run --rm -i ${{ secrets.image-name }} --help