name: Run Performance Analysis
on:
  push

jobs: 
  scan:
    uses: ./.github/workflows/scan-conf-files.yaml
    with:
      directory: "./ci/heart/config" # optional

  pull-image:
    uses: ./.github/workflows/pull-and-cache-docker-image.yaml
    with:
      cache-directory: /cache    
    secrets: 
      image-name: ${{ secrets.HEART_IMAGE_FULL_NAME }}
      registry: ${{ secrets.CONTAINER_REGISTRY_NAME }}
      username: ${{ github.actor }}
      password: ${{ secrets.PAT_TOKEN }}


  batch-analysis:
    runs-on: ubuntu-latest
    needs: [scan, pull-image]

    strategy:
      matrix:
        conf-file-name: ${{ fromJson(needs.scan.outputs.files) }}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Cache Docker image (as tar.gz)
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: heart
      - name: Load Heart image from cache
        run: docker load -i ~/cache/heart.tar.gz
      - name: Retrieve module name from configuration file path
        run: |
          var=$(echo "${{ matrix.conf-file-name }}" | cut -d '/' -f2) | (echo "MODULE_NAME=$var" >> $GITHUB_ENV)
      - name: Check .env variable for module name
        run: |
          echo $MODULE_NAME
      # - name: Retrieve module name from configuration file full path
      #   run: |
      # - name: Run Heart analysis
      #   uses: ./.github/workflows/heart-analysis.yaml
      #   with:
      #     image-name: ${{ secrets.HEART_IMAGE_FULL_NAME }}