name: Pull Heart Docker Image and Cache as tar.gz File

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      registry:
        required: true
        type: string


jobs:
  pull-and-cache-heart-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with: 
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
        # run: echo ${{ inputs.password }} | docker login ghcr.io -u "${{ inputs.username }}" --password-stdin
      - name: Cache Docker image (as tar.gz)
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: heart
      - name: Pull Heart docker image
        run: docker pull ${{ inputs.image-name }}
      - name: Cache Heart Docker image as .tar file
        run: docker save ${{ inputs.image-name }} | gzip > ~/.cache/${inputs.image-name}.tar.gz