name: Pull Heart Docker Image and Cache as tar.gz File

on:
  workflow_call:
    secrets:
      username:
        description: username to login to docker container registry
        required: true
      image-name:
        description: name of the docker image
        required: true
      password:
        description:  password to login to docker container registry
        required: true
      registry:
        description: address of container registry, ex. ghcr.io
        required: true


jobs:
  pull-and-cache-heart-image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.password }}
    steps:
      - name: Login to GitHub container registry
        run: docker login ghcr.io -u "${{ github.actor }}" -p ${{ secrets.password }}
      - name: Cache Docker image (as tar.gz)
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: heart
      - name: Pull Heart docker image
        run: |
          docker pull ghcr.io/fabernovel-fnguyen/heart:latest
      - name: Cache Heart Docker image as .tar file
        run: |
          cd ~
          docker save ${{ secrets.image-name }} | gzip > ~/cache/heart.tar.gz