name: Pull Heart Docker Image and Cache as tar.gz File

on:
  workflow_call:
    inputs:
      cache-directory:
        required: true
        type: string
      registry:
        required: true
        type: string
      image-name:
        required: true
        type: string
    secrets:
      username:
        description: username to login to docker container registry
        required: true
      password:
        description:  password to login to docker container registry
        required: true


jobs:
  pull-and-cache-heart-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub container registry
        run: docker login ghcr.io -u "${{ secrets.username }}" -p ${{ secrets.password }}
      - name: Cache Docker image (as tar.gz)
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/${{ inputs.cache-directory }}
          key: ${{ inputs.image-name }}
      - name: Create cache folder if not already present
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ~
          mkdir ${{ inputs.cache-directory }}
      - name: Pull Heart docker image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ inputs.image-name }}
      - name: Cache Heart Docker image as .tar file
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ~/${{ inputs.cache-directory }}
          docker save ${{ inputs.image-name }} | gzip > ~/${{ inputs.cache-directory }}/heart-image.tar.gz