name: Scan for Configuration Files [Reusable workflow]

on:
  workflow_call:
    inputs:
      directory:
        description: "Heart configuration directory"
        required: true
        type: string
    outputs:
      files: ${{ jobs.scan-conf-files.step2.outputs.files }}

jobs:
  scan-conf-files:
    runs-on: ubuntu-latest
    outputs: 
      files: ${{ steps.config-files.outputs.files }}
    steps:
      - name: Checkout
        id: step1
        uses: actions/checkout@v2
      - name: Identify configuration JSON files in ${{ inputs.directory }}
        id: step2
        working-directory: ${{ inputs.directory }}
        run: |
          echo "::set-output name=files::$(find . -name "*.json" | jq -R -s -c 'split("\n")[:-1]')"
